---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

  pull_request:

permissions:
  contents: read

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"
      - run: script/setup --dev
      - run: script/lint
      - run: script/test
